### ISSUE TITLE
码云上有个相同的项目，请问你俩是谁在抄袭谁

### ISSUE THREAD

**Issue by Willie-lin** [stylefeng/Guns#16]
https://gitee.com/wuburen/guns

**Comment by Pleuvoir** [comment]
码云上是fork的好吗。。

**Comment by fuzhaohao** [comment]
竟然被你发现了 
![image](https://user-images.githubusercontent.com/4248526/38695346-990c9f42-3ebe-11e8-8c95-d57c9a07e8f0.gif)
但是你可以看到下面有一行
![image](https://user-images.githubusercontent.com/4248526/38695247-5124b4b2-3ebe-11e8-951f-8d3518595e59.png)
