### ISSUE TITLE
二次开发问题。

### ISSUE THREAD

**Issue by yangguang111lll** [stylefeng/Guns#21]
其实感觉项目还是有问题的，假如我要开发一个博客模块，后台要维护博客模块，前台要rest api做服务，那么我的模块怎么放啊？难道rest模块和admin模块都要拷贝一份dao service ..的业务代码吗？

**Comment by stylefeng** [comment]
rest模块是单独的，rest模块不建议直接拿来用，拿来用你还需要配置很多，这个模块只是用来参考签名和鉴权机制用的
