### ISSUE TITLE
如何关闭控制台的sql打印以及返回结果？

### ISSUE THREAD

**Issue by zhaoguohui1996** [stylefeng/Guns#99]

**Comment by stylefeng** [comment]
mybatis-plus:
  mapper-locations: classpath*:cn/stylefeng/**/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

**Comment by stylefeng** [comment]
![image](https://user-images.githubusercontent.com/9100555/133379513-e01bd464-019c-41cf-ae31-6a4f43efcdf3.png)
